// components/landing/MatchingExplainerCards.vue
<template>
  <section class="w-full py-12 md:py-16 bg-background relative overflow-hidden">
    <div class="container mx-auto px-4 md:px-6 relative z-10">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 max-w-5xl mx-auto">
        <FlipCard
          v-for="(card, index) in cardsData"
          :key="index"
          :card-data="card"
          :delay="index * 0.15"
        />
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { Rocket, Users, Briefcase, CheckCircle, Sparkles, TrendingUp, Target } from 'lucide-vue-next'
import FlipCard from './FlipCard.vue'

interface Feature {
  icon: any
  text: string
}

interface CardData {
  icon: any
  title: string
  subtitle: string
  description: string
  features: Feature[]
  gradientColors: {
    from: string
    via: string
    to: string
  }
  glowColor: string
}

const cardsData: CardData[] = [
  {
    icon: Users,
    title: 'Pour les Couples',
    subtitle: 'Trouvez vos prestataires idéaux',
    description: 'Décrivez votre événement en 30 secondes et laissez notre algorithme intelligent trouver les prestataires parfaits.',
    features: [
      { icon: Rocket, text: 'Quiz rapide de 3 questions' },
      { icon: Target, text: 'Matching instantané et personnalisé' },
      { icon: CheckCircle, text: 'Profils vérifiés et avis certifiés' }
    ],
    gradientColors: {
      from: '#823F91',
      via: '#c081e3',
      to: '#823F91'
    },
    glowColor: 'rgba(130,63,145,0.6)'
  },
  {
    icon: Briefcase,
    title: 'Pour les Prestataires',
    subtitle: 'Recevez des demandes qualifiées',
    description: 'Créez votre profil et recevez automatiquement des demandes qui correspondent exactement à vos services.',
    features: [
      { icon: Target, text: 'Leads 100% qualifiés et ciblés' },
      { icon: Sparkles, text: 'Zéro prospection nécessaire' },
      { icon: TrendingUp, text: '+40% de réservations en moyenne' }
    ],
    gradientColors: {
      from: '#c081e3',
      via: '#823F91',
      to: '#c081e3'
    },
    glowColor: 'rgba(192,129,227,0.6)'
  }
]
</script>

<style scoped>
/* Respect de prefers-reduced-motion */
@media (prefers-reduced-motion: reduce) {
  * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
</style>

// components/landing/MatchingExplainerCards.tsx
'use client'

import { motion } from 'motion/react'
import FlipCard from '@/components/ui/flip-card'

export default function MatchingExplainerCards() {
  return (
    <section className="w-full py-20 bg-gradient-to-b from-gray-50 to-white">
      {/* Titre de section */}
      <div className="container mx-auto px-4 mb-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Comment fonctionne le matching ?
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Une approche intelligente qui connecte les bons couples avec les bons prestataires
          </p>
        </motion.div>
      </div>

      {/* Deux cartes côte à côte */}
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12 max-w-5xl mx-auto items-center">
          
          {/* Carte 1 : Pour les Couples */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="flex justify-center"
          >
            <FlipCard
              title="Pour les Couples"
              subtitle="Trouvez vos prestataires idéaux"
              description="Décrivez votre événement en 30 secondes et laissez notre algorithme intelligent trouver les prestataires qui correspondent parfaitement à vos besoins, votre budget et votre style."
              features={[
                'Quiz rapide de 3 questions',
                'Matching instantané et personnalisé',
                'Profils vérifiés et avis certifiés',
                '92% de compatibilité moyenne'
              ]}
            />
          </motion.div>

          {/* Carte 2 : Pour les Prestataires */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="flex justify-center"
          >
            <FlipCard
              title="Pour les Prestataires"
              subtitle="Recevez des demandes qualifiées"
              description="Créez votre profil professionnel et recevez automatiquement des demandes de couples qui correspondent exactement à vos services, votre zone et vos disponibilités."
              features={[
                'Leads 100% qualifiés et ciblés',
                'Zéro prospection nécessaire',
                'Visibilité auprès des bons clients',
                '+40% de réservations en moyenne'
              ]}
            />
          </motion.div>

        </div>
      </div>

      {/* Call-to-action subtil (optionnel) */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay: 0.6 }}
        className="container mx-auto px-4 mt-12 text-center"
      >
        <p className="text-sm text-gray-500">
          Survolez les cartes pour découvrir plus de détails
        </p>
      </motion.div>
    </section>
  )
}
